interface MenuSection {
    title: string;
    items: MenuItem[];
}

interface MenuItem {
    title: string;
    price: string;
    img: string;
    weight: string;
    description: string;
    proteins: string;
    fats: string;
    carbs: string;
    calories: string;
}

export const MenuItems: MenuSection[] = [
    {
        title: "Эфиопская кухня",
        items: [
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
        ],
    },
    {
        title: "Эфиопские напитки",
        items: [
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
        ],
    },
    {
        title: "Салаты",
        items: [
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
        ],
    },
    {
        title: "Закуски",
        items: [
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
            {
                title: 'Баранина "Сокота"',
                description: "lorem ipsum lorem ipsum lorem ipsum",
                img: "https://assets.v3.snowfirehub.com/images/120888/499_o_.he-best-image-format-for-the-web-3-quick-SEO-tips-",
                price: "680 Р.",
                calories: "XYZ",
                carbs: "XYZ",
                fats: "XYZ",
                proteins: "XYZ",
                weight: "350 г",
            },
        ],
    },
];
